import { IPerson } from './Types'

const Person: IPerson = {
	name: 'Herman Johannes',
	origin: 'NusaTenggaraTimur',
	image: 'People/HermanJohannes/Card.jpg',
	thumbnail: 'People/HermanJohannes/Thumbnail.jpg',
	imageSource: 'https://id.wikipedia.org/wiki/Herman_Johannes',
	thumbnailSource:
		'https://www.kompas.com/stori/read/2021/07/08/100000179/herman-johannes--masa-muda-peran-dan-kiprah',
	articleSource: 'https://m.merdeka.com/herman-johannes/profil',
	article: `Prof. Dr. Ir. Herman Johannes atau yang sering disebut dengan nama panggilan Pak Jo adalah seorang cendekiawan, politikus serta ilmuwan Indonesia. Pak Jo lahir di desa Keka pulau Rote, NTT pada tanggal 12 Mei 1912 sebagai anak ke 4 pasangan Daniel Abia Johannes dengan istrinya, Aranci Dirk. Herman Johannes muda harus meninggalkan desa dan Sekolah Melayu yang hanya diikutinya selama setahun, agar dapat melanjutkan pendidikannya ke jenjang yang lebih tinggi yaitu pada Europesche Lagere School (ELS) di Kupang.Herman Johannes remaja kemudian berangkat ke Makassar untuk melanjutkan pendidikannya di MULO (Meer Uitgebreid Lager Onderwijs) dan kemudian dilanjutkan ke AMS (Algemeene Middelbare School) di Batavia. Berkat nilainya yang tinggi saat sekolah di AMS, Pak Jo diberikan beasiswa untuk melanjutkan studinya ke Technische Hooge School di Bandung tahun 1934 yang baru dapat diselesaikannya pada tahun 1946.
Semasa kuliah inilah, Pak Jo mulai mengasah kemampuannya dalam menulis karangan ilmiah. Tulisan-tulisannya selalu mendapat perhatian besar dan pujian dari pimpinan fakultas dan kalangan akademisi hingga akhirnya lolos seleksi untuk dimuat dalam majalah De Ingenieur in Nederlandsch Indie dan akhirnya mendapat penghargaan dari Koningklijk Instituut van Ingenieurs di Belanda. Selain aktif dalam menulis, Pak Jo juga aktif berorganisasi. Bersama dengan Simon K.Tibuludji, Izaak Huru Doko, Josef Toelle dan Chris Ndaumanu, Herman mendirikan perkumpulan Timorsche Jongeren yang kemudian dirubah menjadi Perkumpulan Kebangsaan Timor (PKT). Ini merupakan awal keterlibatan Herman dalam bidang politik yang kemudian akan mengantarnya menjadi salah seorang pendiri Partai Indonesia Raya dan menjadi anggota Komite Nasional Indonesia Pusat. Karena pengetahuannya yang tinggi dalam bidang ilmu fisika dan kimia, Herman sering dimintai bantuan oleh para pemuda pejuang untuk merakit senjata api dan membuat detonator serta alat peledak. Kepiawaianya dalam persenjataan akhirnya menarik perhatian Markas Tertinggi Tentara di Yogyakarta, yang kemudian memerintahkannya untuk segera datang ke Yogya guna membuka dan sekaligus memimpin sebuah laboratorium persenjataan. Untuk tugas tersebut Herman diangkat sebagai anggota militer dengan pangkat Mayor. Melalui inilah, akhirnya Pak Jo semakin dalam berkecimpung di dunia militer. dia pernah berperang bersama Letkol Soeharto.
Pada tahun 1950 setelah pengakuan kedaulatan RI oleh Belanda, Pak Jo melepaskan seluruh jabatan dan pangkat kemiliterannya dan kembali mengabdi di bidang pendidikan. Setelah pensiun, Herman sempat dipercaya untuk menjabat sebagai Menteri Pekerjaan Umum dan Tenaga dalam kabinet Moh. Natsir. Selain itu, dia juga kembali menghasilkan banyak karya tulisan. Pada usia 43 tahun. pada bulan Mei 1955 Herman menikah dengan putri seorang raja Rote, Attie M.G. Amalo. Dari perkawinan ini beliau memperoleh 4 orang anak, masing-masing Christine, Henriette, Daniel dan Helmi. Herman Johannes meninggal dunia pada 17 Oktober 1992 karena kanker prostat. Pada tahun 2003, nama Herman Johannes diabadikan oleh Keluarga Alumni Teknik Universitas Gadjah Mada (KATGAMA), atas prakarsa Ketua Katgama saat itu, Airlangga Hartarto, menjadi sebuah penghargaan bagi karya utama penelitian bidang ilmu dan teknologi yakni Herman Johannes Award. Sesuai Keputusan Presiden RI (Keppres) No. 80 Tahun 1996, nama Herman Johannes diabadikan sebagai nama Taman Hutan Raya bagi kelompok hutan Sisinemi-Sanam seluas 1.900 hektare di Kabupaten Kupang, Provinsi Nusa Tenggara Timur. Nama Prof Herman Johannes juga diabadikan menjadi nama jalan yang menghubungkan Kampus UGM dengan Jalan Solo dan Jalan Jenderal Sudirman di kota Yogyakarta.`,
}

export default Person
